### ISSUE TITLE
InternalError (see above for traceback): cuDNN launch failure : input shape([1,3,805,1207]) filter shape([7,7,3,64])

### ISSUE THREAD

**Issue by PacteraOliver** [tensorpack/tensorpack#838]
I am using the Faster RCNN. And I follow the instructions for dataset and weights and run:
```bash
./train.py --evaluate output.json --load /media/workspace/Model/COCO-R50C4-MaskRCNN-Standard.npz --config MODE_MASK=True DATA.BASEDIR=/media/workspace/COCO/DIR/
```

The config is:

```
{'BACKBONE': {'FREEZE_AFFINE': False,
              'FREEZE_AT': 2,
              'NORM': 'FreezeBN',
              'RESNET_NUM_BLOCK': [3, 4, 6, 3],
              'STRIDE_1X1': False,
              'TF_PAD_MODE': False,
              'WEIGHTS': ''},
 'DATA': {'BASEDIR': '/media/workspace/COCO/DIR/',
          'CLASS_NAMES': [],
          'NUM_CATEGORY': 80,
          'NUM_CLASS': 81,
          'TRAIN': ['train2014', 'valminusminival2014'],
          'VAL': 'minival2014'},
 'FPN': {'ANCHOR_STRIDES': (4, 8, 16, 32, 64),
         'FRCNN_CONV_HEAD_DIM': 256,
         'FRCNN_FC_HEAD_DIM': 1024,
         'FRCNN_HEAD_FUNC': 'fastrcnn_2fc_head',
         'MRCNN_HEAD_FUNC': 'maskrcnn_up4conv_head',
         'NORM': 'None',
         'NUM_CHANNEL': 256,
         'PROPOSAL_MODE': 'Level',
         'RESOLUTION_REQUIREMENT': 32},
 'FRCNN': {'BATCH_PER_IM': 512,
           'BBOX_REG_WEIGHTS': [10.0, 10.0, 5.0, 5.0],
           'FG_RATIO': 0.25,
           'FG_THRESH': 0.5},
 'MODE_FPN': False,
 'MODE_MASK': True,
 'MRCNN': {'HEAD_DIM': 256},
 'PREPROC': {'MAX_SIZE': 1333,
             'PIXEL_MEAN': [123.675, 116.28, 103.53],
             'PIXEL_STD': [58.395, 57.12, 57.375],
             'SHORT_EDGE_SIZE': 800},
 'RPN': {'ANCHOR_RATIOS': (0.5, 1.0, 2.0),
         'ANCHOR_SIZES': (32, 64, 128, 256, 512),
         'ANCHOR_STRIDE': 16,
         'BATCH_PER_IM': 256,
         'CROWD_OVERLAP_THRESH': 0.7,
         'FG_RATIO': 0.5,
         'HEAD_DIM': 1024,
         'MIN_SIZE': 0,
         'NEGATIVE_ANCHOR_THRESH': 0.3,
         'NUM_ANCHOR': 15,
         'POSITIVE_ANCHOR_THRESH': 0.7,
         'PROPOSAL_NMS_THRESH': 0.7,
         'TEST_PER_LEVEL_NMS_TOPK': 1000,
         'TEST_POST_NMS_TOPK': 1000,
         'TEST_PRE_NMS_TOPK': 6000,
         'TRAIN_PER_LEVEL_NMS_TOPK': 2000,
         'TRAIN_POST_NMS_TOPK': 2000,
         'TRAIN_PRE_NMS_TOPK': 12000},
 'TEST': {'FRCNN_NMS_THRESH': 0.5,
          'RESULTS_PER_IM': 100,
          'RESULT_SCORE_THRESH': 0.05,
          'RESULT_SCORE_THRESH_VIS': 0.3},
 'TRAIN': {'BASE_LR': 0.01,
           'LR_SCHEDULE': [240000, 320000, 360000],
           'NUM_GPUS': None,
           'STEPS_PER_EPOCH': 500,
           'WARMUP': 1000,
           'WEIGHT_DECAY': 0.0001},
 'TRAINER': 'replicated'}
```

Then the problem is:

```
[0720 14:51:46 @timer.py:48] Load Groundtruth Boxes for minival2014 finished, time:0.0244sec.
  0%|                                                     |0/5000[00:00<?,?it/s]2018-07-20 14:51:47.212606: E tensorflow/stream_executor/cuda/cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-07-20 14:51:47.243910: E tensorflow/stream_executor/cuda/cuda_blas.cc:462] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2018-07-20 14:51:47.426549: E tensorflow/stream_executor/cuda/cuda_dnn.cc:455] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-07-20 14:51:47.426581: E tensorflow/stream_executor/cuda/cuda_dnn.cc:427] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-07-20 14:51:47.426590: W ./tensorflow/stream_executor/stream.h:2023] attempting to perform DNN operation using StreamExecutor without DNN support

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1322, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1307, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1409, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([1,3,805,1207]) filter shape([7,7,3,64])
	 [[Node: conv0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, conv0/W/read)]]
	 [[Node: fastrcnn_predictions/map/while/Shape/_1751 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1406_fastrcnn_predictions/map/while/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfastrcnn_predictions/map/while/SparseToDense/default_value/_1675)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./train.py", line 544, in <module>
    offline_evaluate(pred, args.evaluate)
  File "./train.py", line 457, in offline_evaluate
    df, lambda img: detect_one_image(img, pred_func))
  File "/home/oliver/git/tensorpack/examples/FasterRCNN/eval.py", line 106, in eval_coco
    results = detect_func(img)
  File "./train.py", line 457, in <lambda>
    df, lambda img: detect_one_image(img, pred_func))
  File "/home/oliver/git/tensorpack/examples/FasterRCNN/eval.py", line 75, in detect_one_image
    boxes, probs, labels, *masks = model_func(resized_img)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/predict/base.py", line 51, in __call__
    output = self._do_call(dp)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/predict/base.py", line 150, in _do_call
    return self._do_call_new(dp)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/predict/base.py", line 140, in _do_call_new
    ret = self._callable(*dp)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1187, in _generic_run
    return self.run(fetches, feed_dict=feed_dict, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: cuDNN launch failure : input shape([1,3,805,1207]) filter shape([7,7,3,64])
	 [[Node: conv0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, conv0/W/read)]]
	 [[Node: fastrcnn_predictions/map/while/Shape/_1751 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1406_fastrcnn_predictions/map/while/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfastrcnn_predictions/map/while/SparseToDense/default_value/_1675)]]

Caused by op 'conv0/Conv2D', defined at:
  File "./train.py", line 541, in <module>
    output_names=MODEL.get_inference_tensor_names()[1]))
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/predict/base.py", line 169, in __init__
    config.tower_func(*input.get_input_tensors())
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/tfutils/tower.py", line 255, in __call__
    output = self._tower_fn(*args)
  File "./train.py", line 170, in build_graph
    featuremap = resnet_c4_backbone(image, cfg.BACKBONE.RESNET_NUM_BLOCK[:3])
  File "/home/oliver/git/tensorpack/examples/FasterRCNN/basemodel.py", line 151, in resnet_c4_backbone
    l = Conv2D('conv0', l, 64, 7, strides=2, padding='VALID')
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/registry.py", line 124, in wrapped_func
    outputs = func(*args, **actual_args)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/tflayer.py", line 64, in decorated_func
    return func(inputs, **ret)
  File "/usr/local/lib/python3.6/dist-packages/tensorpack/models/conv2d.py", line 68, in Conv2D
    ret = layer.apply(inputs, scope=tf.get_variable_scope())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py", line 828, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/layers/convolutional.py", line 168, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 868, in __call__
    return self.conv_op(inp, filter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 520, in __call__
    return self.call(inp, filter)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py", line 204, in __call__
    name=self.name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 956, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): cuDNN launch failure : input shape([1,3,805,1207]) filter shape([7,7,3,64])
	 [[Node: conv0/Conv2D = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, conv0/W/read)]]
	 [[Node: fastrcnn_predictions/map/while/Shape/_1751 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1406_fastrcnn_predictions/map/while/Shape", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopfastrcnn_predictions/map/while/SparseToDense/default_value/_1675)]]
```

Any ideas?

**Comment by ppwwyyxx** [comment]
The log is quite clear that you have environment problems with your cuda/cudnn.

**Comment by PacteraOliver** [comment]
@ppwwyyxx 
Hi, thank you for your update.

I could successfully run the [tf-faster-rcnn](https://github.com/endernewton/tf-faster-rcnn) before or other models which need cuda/cudnn. 

I will try with docker to build the environment. Hope it could fix the environment problem.

**Comment by PacteraOliver** [comment]
@ppwwyyxx 

I fixed this problem by run as root.

**Comment by hanfeng0409** [comment]
@PacteraOliver hello, i have the same problem now, and solve it thanks to your advice. But i can't understand, do u know why it need root? Thanks~
