### ISSUE TITLE
Tensorpack hogging GPU memory 

### ISSUE THREAD

**Issue by hesz94** [tensorpack/tensorpack#937]
As in the description, I've been trying to use tensorpack to train a custom CNN on 2 gpus, however tensorpack seems to be hogging large amounts of memory - if I'm training using basic tensorflow code (optimizer.minimize()) I can use a batch size of 64 per GPU, with tensorpack I get OOM for anything above 1.

At first I suspected that this was due to QueueInput defaulting to queue length of 50 and perhaps reserving the gpu memory (would explain why batch size of 1 worked, but 2 threw a memory error), however manually setting queueinput and reducing the length didn't change anything.

`from src.tf.utils.modelwrapper import CustomModelDesc
from src.tf.utils.bcdataflow import CustomDataFlow
import tensorflow as tf
from tensorpack import *

%env TF_CUDNN_USE_AUTOTUNE=0

extra_display = ["loss"]

ds = CustomDataFlow()
ds = QueueInput(ds, tf.FIFOQueue(2, [tf.float32 for i in range(8)]))
ds = StagingInput(ds, nr_stage=1, device='/cpu:0')

callbacks=[
            ModelSaver(checkpoint_dir='some_save_path', max_to_keep=3, 
                       keep_checkpoint_every_n_hours=1),
            ScheduledHyperParamSetter('learning_rate',
                                    [(0, 1e-3), (200, 1e-4), (400, 1e-5), (600, 1e-6), (800, 1e-7)])
            ]

extra_callbacks=[  
                ProgressBar(extra_display),
                ]
monitors=[    
        ScalarPrinter(enable_step=True),
        ]

config = TrainConfig(
    model=CustomModelDesc(),
    data=ds,
    max_epoch=1000,
    session_init=SaverRestore('some_path'),
    callbacks=callbacks,
    extra_callbacks=extra_callbacks,
    monitors=monitors, 
)

launch_train_with_config(config, SyncMultiGPUTrainerParameterServer(num_gpus))`

Note that the result was exactly the same without specifying QueueInput and StagingInput, as well as without "%env TF_CUDNN_USE_AUTOTUNE=0" (ran in jupyter)

Both towers are built, trainable variables are displayed correctly. Callbacks get set up, model checkpoint gets loaded, graph is finalized. Then it moves to:
[1020 12:39:30 @input_source.py:513] Pre-filling StagingArea ...
[1020 12:39:30 @input_source.py:517] 1 element was put into StagingArea.
[1020 12:41:44 @input_source.py:150] EnqueueThread fifo_queue Exited.

And crashes after about a minute, resulting in (batch size of 4 per gpu in this case):
ResourceExhaustedError: OOM when allocating tensor of shape [4,304,304,64] and type float

I'm almost certain I'm missing some obvious step that would limit needless gpu memory allocation, but I'm not sure what it could be.

The tensorflow counterpart that handles batch size of 64 without hiccups is:
`sess = tf.Session()
optimizer = tf.train.AdamOptimizer()
train = optimizer.minimize(loss)
sess.run(tf.global_variables_initializer())
sess.run(train, feed_dict=sample_data)`

**Comment by ppwwyyxx** [comment]
I would assume you've made some mistakes in the model code so it actually is something else. But without enough details I cannot help. You can easily verify that the official examples can all run with a large batch size (e.g. ResNet50 can run with a batch size of 128 on 16GB GPU).

Also try removing stagingarea to see if it changes anything.

**Comment by ppwwyyxx** [comment]
Also, to report any unexpected issues please always post __full log__ rather than describing what you saw. Even you don't want to post code, logs can still be helpful. Another hypothesis is that you've manually created a session that takes all memory before starting tensorpack trainer. With logs this can be easily seen.

See https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md on how to write an issue.

**Comment by hesz94** [comment]
Forgot to post the update, sorry about that!

Turns out there was a bug in the code for building the model for regular tf trainer (missed a line) so that's why it could fit much larger training batches. Turns out that in the end it's just the fact that the model is massive, and nothing was wrong on the side of tensorpack.

Thanks for the tips and sorry for the trouble!
